[package]
name = "lending_core"
version = "1.3.0"
published-at = "0xee0041239b89564ce870a7dec5ddc5d114367ab94a1137e90aa0633cb76518e0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"

[dependencies.math]
path = "../math"

[dependencies.oracle]
path = "../oracle"

[dependencies.utils]
path = "../utils"

[dependencies.liquid_staking]
path = "../volo_liquid_staking"

[addresses]
sui = "0x2"
lending_core = "0xd899cf7d2b5db716bd2cf55599fb0d5ee38a3061e7b6bb6eebf73fa5bc4c81ca"
