[published.mainnet]
chain-id = "35834a8a"
published-at = "0x1e4a13a0494d5facdbe8473e74127b838c2d446ecec0ce262e2eddafa77259cb"
original-id = "0xd899cf7d2b5db716bd2cf55599fb0d5ee38a3061e7b6bb6eebf73fa5bc4c81ca"
version = 24

[published.development]
chain-id = "35834a8a"
published-at = "0x239b6bf3e23ca581af9c7475ad84e909256b9e04b4c29e8782dfae3179e8f2d9"
original-id = "0xa49c5d1c8f0a9eaa4e1c0c461c2b5dfb6e88213876739e56db1afb3649a8af26"
version = 10

[published.deps]
chain-id = "35834a8a"
published-at = "0x57085c1f4a2d163d23aae1906e8055f80cf856464ac4fc55d6f05f4c863b9588"
original-id = "0x57085c1f4a2d163d23aae1906e8055f80cf856464ac4fc55d6f05f4c863b9588"
version = 1
