[package]
name = "liquid_staking"
version = "0.0.1"
published-at = "0x634511c660964940915acb37dde75963e35f2d1b0a034b41e2da8f3e9d1491ae"
edition = "2024"

[addresses]
liquid_staking = "0x634511c660964940915acb37dde75963e35f2d1b0a034b41e2da8f3e9d1491ae"
