[published.mainnet]
chain-id = "35834a8a"
published-at = "0x634511c660964940915acb37dde75963e35f2d1b0a034b41e2da8f3e9d1491ae"
original-id = "0x634511c660964940915acb37dde75963e35f2d1b0a034b41e2da8f3e9d1491ae"
version = 10
