[published.mainnet]
chain-id = "35834a8a"
published-at = "0xc2d49bf5e75d2258ee5563efa527feb6155de7ac6f6bf025a23ee88cd12d5a83"
original-id = "0xca441b44943c16be0e6e23c5a955bb971537ea3289ae8016fbf33fffe1fd210f"
version = 3

[published.development]
chain-id = "35834a8a"
published-at = "0x932348042715171fd1ef651752bf2dc6f3b3d6688e0dc02bad8f6e9ed2080bd7"
original-id = "0x859de5e155d57462d3fe0aeb980b9a3f9cdccf76522d9499f372789183440aca"
version = 2
