[published.mainnet]
published-at = "0xee0041239b89564ce870a7dec5ddc5d114367ab94a1137e90aa0633cb76518e0"
original-id = "0xd899cf7d2b5db716bd2cf55599fb0d5ee38a3061e7b6bb6eebf73fa5bc4c81ca"
version = 23

[published.development]
published-at = "0x239b6bf3e23ca581af9c7475ad84e909256b9e04b4c29e8782dfae3179e8f2d9"
original-id = "0xa49c5d1c8f0a9eaa4e1c0c461c2b5dfb6e88213876739e56db1afb3649a8af26"
version = 10

[published.deps]
published-at = "0x57085c1f4a2d163d23aae1906e8055f80cf856464ac4fc55d6f05f4c863b9588"
original-id = "0x57085c1f4a2d163d23aae1906e8055f80cf856464ac4fc55d6f05f4c863b9588"
version = 1
